config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get '/about', to: 'pages#about'

  get '/contact', to: 'pages#contact'

  get '/form', to: 'pages#form'

  get '/techniques', to: 'pages#techniques'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_copyright

    def set_copyright
      @copyright = BigMouthFrogCopyrightTool::Renderer.copyright("Big Mouth Frog Development", "All rights reserved")
    end
  end

  module BigMouthFrogCopyrightTool
    class Renderer
      def self.copyright name, msg
        "&copy; #{Time.now.year} | Powered by: <a href='https://bigmouthfrogdev.com' target='_blank'>#{name}</a> | #{msg}".html_safe
      end
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def form
  end

  def technique
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(path)
    "active" if current_page?(path)
  end
  def crumb_active?(path)
    "crumb_active" if current_page?(path)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Indemandhandyman</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'logo.png' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<%= render "shared/breadcrumb" %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-4">
          <%= image_tag "jared.jpg", class: "jared" %>
        </div>
        <div class="col-md-8">
          <p class="card">
            Veibulum id ligula porta felis euismod semper. Maecenas faucibus mollis interdum. Maecenas sed diam eget risus varius blandit sit amet non magna. Nullam quis risus eget urna mollis ornare vel eu leo. Nullam quis risus eget urna mollis ornare vel eu leo. Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Aenean lacinia bibendum nulla sed consectetur. Cras mattis consectetur purus sit amet fermentum. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean lacinia bibendum nulla sed consectetur. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-7">
			<div class="map">
				<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1560800.2777318733!2d-111.535794!3d40.177064!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x874d961b01922fd5%3A0xfbd27ed382db18cf!2sUtah+County%2C+UT!5e0!3m2!1sen!2sus!4v1508266372437" width="498" height="498" frameborder="0" style="border:0" allowfullscreen></iframe>
			</div>
		</div>

		<div class="col-md-3 contact-info">
			<div class="card">
				<div class="row">
					<div class="col-md-12 center">
						Hours:
					</div>
				</div>
				<div class="row">
					<div class="col-md-7">
						<ul class="no-list days">
							<li>Monday</li>
							<li>Tuesday</li>
							<li>Wednesday</li>
							<li>Thursday</li>
							<li>Friday</li>
						</ul>
					</div>
					<div class="col-md-5">
						<ul class="no-list hours">
							<li>8-5</li>
							<li>8-5</li>
							<li>8-5</li>
							<li>8-5</li>
							<li>8-5</li>
						</ul>
					</div>
				</div>
			</div>

			<div class="card">
				<ul class="no-list">
					<li>
						Call us: 123-345-6789
					</li>
					<li>
						<%= link_to 'Fill out an estimate', form_path %>
					</li>
					<li>
						<a class="email" href="mailto:jared@indemandhandyman.services">Email Us</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/pages/form.html.erb
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfU5cbVqafx1QmyRpwCWUWILSeQyvPqU8kRswF1WnwbI6Lfhw/viewform?embedded=true" width="100%" height="1200px" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

app/views/pages/home.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <div class="row">
            <h1 class="display-3 col-md-8">In Demand Handyman</h1>
            <p class="lead col-md-3">For your everyday handyman needs.</p>
        </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="card trim-card">
        <%= image_tag "trim.png", class: "trim" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card home-card">
        <p>
          Donec ullamcorper nulla non metus auctor fringilla. Maecenas sed diam eget risus varius blandit sit amet non magna. Donec ullamcorper nulla non metus auctor fringilla. Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
        </p>
      </div>
      <div class="card home-card">
        <p>
          Curabitur blandit tempus porttitor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/pages/techniques.html.erb
<%= render "shared/breadcrumb" %>
<h1 class="center header">Techniques</h1>

<div class="album text-muted">
  <div class="container">

    <div class="row">
      <div class="grid-align"></div>

      <div class="col-md-3 technique-card">
        <img data-src="holder.js/100px280/thumb" alt="Door">
        <p class="technique-card-text">This is a wider technique-card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
      <div class="col-md-1"></div>

      <div class="col-md-3 technique-card">
        <img data-src="holder.js/100px280/thumb" alt="Trim">
        <p class="technique-card-text">This is a wider technique-card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
      <div class="col-md-1"></div>

      <div class="col-md-3 technique-card">
        <img data-src="holder.js/100px280/thumb" alt="Window">
        <p class="technique-card-text">This is a wider technique-card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>

    <div class="row">
      <div class="grid-align"></div>

      <div class="col-md-3 technique-card">
        <img data-src="holder.js/100px280/thumb" alt="Drywall">
        <p class="technique-card-text">This is a wider technique-card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
      <div class="col-md-1"></div>

      <div class="col-md-3 technique-card">
        <img data-src="holder.js/100px280/thumb" alt="Trim">
        <p class="technique-card-text">This is a wider technique-card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
      <div class="col-md-1"></div>

      <div class="col-md-3 technique-card">
        <img data-src="holder.js/100px280/thumb" alt="Caulking">
        <p class="technique-card-text">This is a wider technique-card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>

    <div class="row">
      <div class="grid-align"></div>

      <div class="col-md-3 technique-card">
        <img data-src="holder.js/100px280/thumb" alt="Toilet">
        <p class="technique-card-text">This is a wider technique-card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
      <div class="col-md-1"></div>
      <div class="col-md-3 technique-card">
        <img data-src="holder.js/100px280/thumb" alt="Sink">
        <p class="technique-card-text">This is a wider technique-card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
      <div class="col-md-1"></div>
      <div class="col-md-3 technique-card">
        <img data-src="holder.js/100px280/thumb" alt="Shower">
        <p class="technique-card-text">This is a wider technique-card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>

  </div>
</div>

app/views/shared/_breadcrumb.html.erb
<div class="container">
  <div class="col-md-12">
    <ol class="breadcrumb">
      <li class="breadcrumb-item <%= crumb_active?(about_path)%>"><%= link_to "About the Handyman", about_path %> </li>
      <li class="breadcrumb-item <%= crumb_active?(techniques_path)%>"><%= link_to "Techniques", techniques_path%></li>
    </ol>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-5 center brand-name-footer">
        In Demand Handyman
        <div class="col-md-12 center social-links">
          <i class="fa fa-facebook-square" aria-hidden="true"></i>
        </div>
      </div>
      <div class="col-md-1"></div>
      <div class="col-md-6 center">
        <ul class="no-list">
          <li><a class="email" href="mailto:jared@indemandhandyman.services">Email Us</a></li>
          <li><%= link_to "Free Estimate", form_path %></li>
          <li>123-456-7890</li>
      </ul>
      </div>

    </div>
    <div class="row">
      <div class="col-md-12">
        <p class="copyright"><%= @copyright %></p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<ul class="nav nav-tabs nav-background">
	<li>
		<%= image_tag 'logo.png', class: 'logo' %>
	</li>
	<li class="col-md-4 nav-col">
		<h3 class="brand-name">In Demand Handyman</h3>
	</li>
  <li class="nav-item <%= active?(root_path)%> nav-col">
		<%= link_to 'Home', root_path, class: "nav-link" %>
  </li>
  <li class="nav-item <%= active?(about_path)%> <%= active?(techniques_path)%> nav-col">
		<%= link_to 'About', about_path, class: "nav-link" %>
  </li>
  <li class="nav-item <%= active?(contact_path)%> nav-col">
		<%= link_to 'Contact', contact_path, class: "nav-link" %>
  </li>
  <li class="nav-item <%= active?(form_path)%> nav-col">
		<%= link_to 'Estimate', form_path, class: "nav-link" %>
  </li>
	<li class="number right nav-col">
		<h4>123-345-6789</h4>
	</li>
</ul>